name: AuroraAPI
main: abc.fliqq.auroramc.AuroraAPI
version: '1.0'
author: Fliqq
api-version: '1.21.4'
description: AuroraMC API
commands:
  customcraft:
    usage: /<command>
    permission: auroramc.customcraft
    permission-message: You do not have permission to use this command.
    aliases: [cr, cc]
  testcommand:
    description: Donne une épée avec le flag HIDE_ATTRIBUTES.
    usage: /testcommand

