# Database 
database:
  type: MYSQL # SQLITE, MYSQL
  mysql:
    host: localhost
    port: 3306
    database: auroramc
    username: admin
    password: mtheo
    ssl: false
  
# Modules
modules:
  # Enable or disable modules
  customcraft: true
  duel: false
  
# Global
settings:
  prefix: '&8[&bAurora&6MC&8] &r'